---
language: generic
sudo: required

services:
  - docker

env:
  - APP=node_exporter VERSION=0.16.0 LATEST=1
  - APP=node_exporter VERSION=0.15.2
  - APP=prometheus VERSION=2.3.2 LATEST=1
  - APP=prometheus VERSION=2.2.1
  - APP=prometheus VERSION=2.0.0
  - APP=grafana VERSION=5.2.1 LATEST=1
script:
  - bash -x .travis/build.sh
